# Generated by Django 5.1.1 on 2024-10-07 00:17

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_buyer_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='last_name',
        ),
        migrations.AddField(
            model_name='buyer',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='birth_date',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer',
            name='full_name',
            field=models.CharField(default=datetime.date(2000, 1, 1), max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer',
            name='password',
            field=models.CharField(default=datetime.date(2000, 1, 1), max_length=18, validators=[django.core.validators.MinLengthValidator(6)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer',
            name='username',
            field=models.CharField(default='2000-01-01', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
