# Generated by Django 5.1.1 on 2024-10-07 00:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_buyer_first_name_remove_buyer_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
