# Generated by Django 5.1.1 on 2024-10-07 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_buyerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerprofile',
            name='birth_date',
        ),
    ]
